[project]
name = "vst"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.8"
dependencies = [
    "pandas>=2.2.3",
    "sentence-transformers>=4.0.2",
    "streamlit==1.45.0",
]
